# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def find_sum_of_even_fib(n, elem_one=1, elem_two=2):
    sum_of_even_fib = 0
    while elem_two <= n:
        if elem_two % 2 == 0:
            sum_of_even_fib += elem_two
        elem_temp = elem_two
        elem_two = elem_one + elem_two
        elem_one = elem_temp
    return sum_of_even_fib

print(find_sum_of_even_fib(4000000))